version: '3'

services:
  app:
    image: 'backend:latest'
    container_name: 'spring-boot'
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - spring.env # Containing SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD & SPRING_JPA_HIBERNATE_DDL_AUTO

  db:
    image: 'postgres:15.0-alpine'
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - postgres.env # Containing POSTGRES_USER, POSTGRES_PASSWORD & POSTGRES_DB
    restart: unless-stopped
