version: '3'

services:
  app:
    image: 'backend:latest'
    container_name: 'spring-boot'
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - spring.env

  db:
    image: 'postgres:15.0-alpine'
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    restart: unless-stopped
